[package]
name = "Server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
sqlx = { version = "0.8.3", features = ["runtime-async-std-native-tls", "postgres"] }
tokio = "1.42.0"
uuid = { version = "1.12.0", features = ["v4"] }

